version: 2.1
jobs:

  build:
    parameters:
      path:
        type: string
        default: ""
    docker:
      - image: circleci/node:9

    working_directory: ~/repo/

    steps:
      - checkout
      - run: |
          cd "<< parameters.path >>"
          yarn
          yarn build

workflows:
  version: 2.1
  build_all:
    jobs:
      - build:
          path: "Angular InstantSearch/loading-indicator"
      - build:
          path: "Angular InstantSearch/algolia-insights"
