version: 2.1
jobs:

  build:
    parameters:
      path:
        type: string
        default: "Angular InstantSearch/infinite-scroll"
    docker:
      - image: circleci/node:9

    working_directory: ~/repo/

    steps:
      - checkout

      - run: echo $(ls -1 "<< parameters.path >>")

workflows:
  version: 2.1
  build_all:
    jobs:
      - build
