version: 2.1
commands:
  build_project:
    description: "Building << path >>..."
    parameters:
      path:
        type: string
        default: ""
    steps:
      - checkout
      - run: |
          cd "<< parameters.path >>"
          yarn
          yarn build
jobs:
  build:
    parameters:
      path:
        type: string
        default: ""
    docker:
      - image: circleci/node:9

    working_directory: ~/repo/

    steps:
      - build_project:
          path: "Angular InstantSearch/loading-indicator"
