version: 2.1
jobs:

  build:
    parameters:
      path:
        type: string
        default: ""
    parallelism: 3
    docker:
      - image: circleci/node:9

    working_directory: ~/repo/

    steps:
      - checkout
      - run: echo $(ls -1 "<< parameters.path >>")

workflows:
  version: 2.1
  build_all:
    jobs:
      - build:
          path: "Angular InstantSearch/loading-indicator"
      - build:
          path: "Angular InstantSearch/algolia-insights"
