version: 2.1

executors:
  node9:
    docker:
      - image: circleci/node:9

commands:
  build_project:
    description: "Building << path >>..."
    parameters:
      path:
        type: string
        default: ""
    steps:
      - run:
          name: "Building << parameters.path >>"
          command: |
            cd "<< parameters.path >>"
            yarn
            yarn build
jobs:
  build_angular_projects:
    executor: node9
    steps:
      - checkout
      - build_project:
          path: "Angular InstantSearch/loading-indicator"
      - build_project:
          path: "Angular InstantSearch/algolia-insights"
      - build_project:
          path: "Angular InstantSearch/autocomplete-results-page"
      - build_project:
          path: "Angular InstantSearch/debounced-search-box"
      - build_project:
          path: "Angular InstantSearch/extending-widgets"
      - build_project:
          path: "Angular InstantSearch/geo-search"
      - build_project:
          path: "Angular InstantSearch/getting-started"
      - build_project:
          path: "Angular InstantSearch/infinite-scroll"
      - build_project:
          path: "Angular InstantSearch/loading-indicator"
      - build_project:
          path: "Angular InstantSearch/manipulating-lists/filtering"
      - build_project:
          path: "Angular InstantSearch/manipulating-lists/sorting"
      - build_project:
          path: "Angular InstantSearch/multi-index-autocomplete"
      - build_project:
          path: "Angular InstantSearch/multi-index-hits"
      - build_project:
          path: "Angular InstantSearch/places"
      - build_project:
          path: "Angular InstantSearch/query-suggestions"
      - build_project:
          path: "Angular InstantSearch/refresh"
      - build_project:
          path: "Angular InstantSearch/routing-angular-router"
      - build_project:
          path: "Angular InstantSearch/routing-basic"
      - build_project:
          path: "Angular InstantSearch/routing-full-url"
      - build_project:
          path: "Angular InstantSearch/routing-state-mapping"
      - build_project:
          path: "Angular InstantSearch/secured-api-keys"

  build_react_projects:
    executor: node9
    steps:
      - checkout
      - build_project:
           path: "React InstantSearch/autocomplete-mentions"
      - build_project:
           path: "React InstantSearch/autocomplete-results-page"
      - build_project:
           path: "React InstantSearch/extending-widgets"
      - build_project:
           path: "React InstantSearch/getting-started"
      - build_project:
           path: "React InstantSearch/infinite-scroll"
      - build_project:
           path: "React InstantSearch/multi-index-autocomplete"
      - build_project:
           path: "React InstantSearch/multi-index-hits"
      - build_project:
           path: "React InstantSearch/places"
      - build_project:
           path: "React InstantSearch/query-suggestions"
      - build_project:
           path: "React InstantSearch/routing-basic"
      - build_project:
           path: "React InstantSearch/routing-seo-friendly"
      - build_project:
           path: "React InstantSearch/routing-user-friendly"
      - build_project:
           path: "React InstantSearch/secured-api-keys"


workflows:
  version: 2.1
  build:
    jobs:
      - build_angular_projects
      - build_react_projects
